CREATE SEQUENCE DELIVERY_ITEM_SEQ
START WITH 71016
INCREMENT BY 1
NOCACHE
NOCYCLE;

SELECT DELIVERY_ITEM_SEQ.NEXTVAL
FROM DUAL;

INSERT INTO DELIVERY_ITEM
(
    DELIVERY_ITEM_ID,
    DESCRIPTION,
    STAFF_ID
)
VALUES
(
    DELIVERY_ITEM_SEQ.NEXTVAL,
    'Delivery of office equipment',
    51014
);

COMMIT;

SELECT *
FROM DELIVERY_ITEM
WHERE DELIVERY_ITEM_ID >= 71016;